import { requestToBodyStream } from 'next/dist/server/body-streams'
import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'
import axios from 'axios'




export default function Home({results}) {

  return (
    <div >
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <meta http-equiv="refresh" content="60" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    
      <Nav />

      <Results results={results} />
    </div>
  );
  }

export async  function  getServerSideProps(context) {
    const genre = context.query.genre;

    const request = await fetch(`https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrendings.url}`)
      .then((res) => res.json())
    console.log(request)

    return {
      props :  {
        results : JSON.parse(JSON.stringify(request.results)),
      },
    }
  }



  